spring:
  profiles:
    active: local # default environment

# local 
---
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(yyIMyOETkP0VoQlFimuVxq0De8Jrs+X0ojdmPF+KbJ7bbydyeDPWnWrr9OHkABFf)
    username: ENC(dMneCuujW3XvxIkfYQqIYQ==)
    password: ENC(dMneCuujW3XvxIkfYQqIYQ==)
    
---    
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(yyIMyOETkP0VoQlFimuVxq0De8Jrs+X0ojdmPF+KbJ7bbydyeDPWnWrr9OHkABFf)
    username: ENC(dMneCuujW3XvxIkfYQqIYQ==)
    password: ENC(dMneCuujW3XvxIkfYQqIYQ==)
    
---
spring:
  profiles: prd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(yyIMyOETkP0VoQlFimuVxq0De8Jrs+X0ojdmPF+KbJ7bbydyeDPWnWrr9OHkABFf)
    username: ENC(dMneCuujW3XvxIkfYQqIYQ==)
    password: ENC(dMneCuujW3XvxIkfYQqIYQ==)

---

# Hibernate config
spring:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    database: MYSQL
# Show or not log for each sql query
    show-sql: true
# mail service config
  mail:
    host: smtp.gmail.com
    port: 587
    username: email address
    password: email password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor  

# notification config    
notification:
  cron:
    schedule: 0 0/5 * * * ?
  slack:
    useYn: Y
    webhookUrl: https://hooks.slack.com/services/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
  gmail:
    useYn: Y
    target: target email address here